name: PlatformIO CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Create config.h
        working-directory: ./firmware
        run: cp config/config.h.template config/config.h

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload artifact on ubuntu-latest
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32doit-devkit-v1/firmware.bin

      - name: Output artifact URL
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
